# Generated by Django 3.0.3 on 2020-05-05 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200505_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 21, 8, 27, 449779, tzinfo=utc)),
        ),
    ]
